name: crud_flutter_api
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.7
  animated_text_kit: ^4.2.2
  intl: ^0.18.1
  http: ^1.1.0
  bot_toast: ^4.0.4
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  animations: ^2.0.3
  font_awesome_flutter: ^10.1.0
  carousel_slider: ^4.2.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0

  


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/img/
    - assets/gif/
    - assets/images/start/

